### ISSUE TITLE
NameError: global name 'connection' is not defined

### ISSUE THREAD

**Issue by Ravi355** [fnk0c/cangibrina#6]
Hello, when i run the you're script on ubuntu 16.04, I have following erro:

Traceback (most recent call last):
  File "Admin.py", line 191, in <module>
    target_result = str(check_target(target, args.UserAgent, args.tor))
  File "Admin5.py", line 81, in check_target
    conn = connection.conn(target, UserAgent)
NameError: global name 'connection' is not defined

Help Me,
Best Regards,

**Comment by fnk0c** [comment]
Hello, @Ravi355, first of all, thank you for the report.

Did you renamed the files? I'm asking it because according to your error message there is a file named __Admin.py__ and __Admin5.py__. 
If not, could you send me the command line you're typing?

Best Regards

**Comment by Ravi355** [comment]
Thank you for the quick reply.
Sorry,
I renamed file, 
command line I typed :  $ python Admin5.py   -u example.com

I imported modules are:

from sys import path, argv
import argparse
path.append("src")
import connections

#import scans
from theano import scan

from time import sleep
from threading import Thread, active_count

Best Regards,

**Comment by fnk0c** [comment]
I believe the error is a typo. 

you're doing `import connections` when it was supposed to be `import connection` without the **s** at the end.

**Comment by Ravi355** [comment]
I got following error:

Traceback (most recent call last):
  File "Admin5.py", line 27, in <module>
    import connection
ImportError: No module named connection

**Comment by fnk0c** [comment]
Do you have the following files inside the _src_ directory?

1. banner
2. connection.py
3. scans.py

Also, are you modifing the script? Because I'm failing to see why this error is occoruing

**Comment by Ravi355** [comment]
Hello, 
I am pleased to inform you that, It's not you're script error. It's my fault.
Thanks for everything you do for me.

Best Regards,

**Comment by fnk0c** [comment]
Glad to know everything is fine now.
You're welcome and don't hesitate in open other issues if needed.

Good Luck
